export const tagList = [
    {
        id: 1,
        name: "步兵"
    }, {
        id: 2,
        name: "骑兵"
    }, {
        id: 3,
        name: "射手"
    }, {
        id: 4,
        name: "骑射手"
    }, {
        id: 5,
        name: "长矛兵"
    }, {
        id: 6,
        name: "冲击步兵"
    }, {
        id: 7,
        name: "火药部队"
    }, {
        id: 8,
        name: "战象"
    }, {
        id: 9,
        name: "僧侣"
    }, {
        id: 10,
        name: "独特部队"
    }, {
        id: 11,
        name: "掷矛手"
    }, {
        id: 13,
        name: "骆驼"
    }, {
        id: 14,
        name: "马穆鲁克"
    }, {
        id: 5,
        name: "舰船"
    }, {
        id: 11,
        name: "掷矛手"
    }, {
        id: 13,
        name: "骆驼"
    }, {
        id: 14,
        name: "马穆鲁克"
    }, {
        id: 15,
        name: "攻城武器"
    }, {
        id: 16,
        name: "重型攻城武器"
    }, {
        id: 17,
        name: "冲车"
    }, {
        id: 18,
        name: "舰船"
    }, {
        id: 19,
        name: "远程舰船"
    }, {
        id: 20,
        name: "喷火船"
    }, {
        id: 21,
        name: "英雄"
    }, {
        id: 22,
        name: "建筑"
    }, {
        id: 23,
        name: "石制建筑"
    }, {
        id: 24,
        name: "石墙和门"
    }
]